//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaintClicker.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public string Name { get; set; }
        public int PaintChips { get; set; }
        public int PaintChunks { get; set; }
        public int Chisels { get; set; }
        public int Workers { get; set; }
        public int Mixers { get; set; }
    }
}
