//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaintClicker.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Research
    {
        public string UserName { get; set; }
        public bool PaintThinner { get; set; }
        public bool Steriods { get; set; }
        public bool Prosthetics { get; set; }
        public bool NanoBots { get; set; }
        public bool ElectricChisels { get; set; }
        public bool PlasmaChisels { get; set; }
        public bool QuantumChisels { get; set; }
        public bool AntiMatterChisels { get; set; }
        public bool Oscilators { get; set; }
        public bool PaintCollider { get; set; }
        public bool Multiverse { get; set; }
    }
}
